#!/bin/sh

PROJECT_ROOT=/path/to/project
BINDIR=/usr/bin
SBINDIR=/usr/sbin
HOYADIR=/path/to/Hoya

SERVER_USER=apache
SERVER_PORT=5000

HOST=www.example.com

exec 2>&1
cd $PROJECT_ROOT || exit 1
exec \
  $SBINDIR/setuidgid $SERVER_USER \
  $BINDIR/plackup \
  -R www,pl,lib,conf,$HOYADIR \
  --port=$SERVER_PORT \
  --host=$HOST \
  -I $HOYADIR/lib \
  -I $HOYADIR/extlib \
  -I lib \
  -s Starman \
  $PROJECT_ROOT/www/index.psgi
#  -s HTTP::Server::PSGI \
#  --max-workers 1 \
#  -L Loader::Restarter\

