#--------------------------------------------------------------------------------
#
#  base.yml
#    基本設定ファイル
#    Hoya::Config が使用する
#
#--------------------------------------------------------------------------------
---
LOCAL: 1

PROJECT_NAME: my project
YEAR_RELEASE: 2010

WEBSITE_NAME: welcome to my project

PAGE:
  CSS_COMMON: [_base, _layout, _additional]
  JS_COMMON:  [_base, _additional]

DSH:
  DBI:  0
  YAML: 1

DB:
  TYPE:   mysql
  NAME:   dbname
  HOST:   localhost
  USER:   user
  PASSWD: password
  TABLE_PREFIX: pre_

COOKIE:
  EXPIRES: +14d
  DOMAIN:  
  PATH:    /
  SECURE:  0

CACHE:
  ENABLED:   1
  NAMESPACE: hoya
  EXPIRES:   600

MAIL:
  HOST_SMTP: localhost:587
  ADDRESS:
    FROM: noreply@example.com
    CC:
  SIGNATURE: |
    --
    your email signature.

CONTENT_TYPE_DEFAULT: 'text/html; charset=utf-8'
